### PR TITLE
Add support for VS 2022

### LINKED ISSUE #99: Visual Studio 2022 Support
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

### PR DESCRIPTION
**Pull request by NGumby**
Fixes #99 
Based on the work of https://github.com/chenxustu1/FileNesting

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks for the PR. Unfortunately, your approach will result in the extension no longer working in previous versions of Visual Studio . Fo full support, this extension must be split in two.

**Comment by blackboxlogic** [comment]
Would it work to merge this PR then publish the extension to the VS marketplace with a different identifier? The 2017 compatible version could remain (though, be difficult to maintain) and a 2022 version would be newly available.
(I don't know much about how marketplace.visualstudio.com works)

**Comment by Griffork** [comment]
Create a branch of the old one for patching and then merge the new one into master and deploy it as a new extension to the marketplace?

**Comment by LaraSQP** [comment]
> Fixes #99 Based on the work of https://github.com/chenxustu1/FileNesting

Much appreciated

**Comment by AdmiralSnyder** [comment]
@madskristensen 
hey Mads, in one of my extensions, https://marketplace.visualstudio.com/items?itemName=AlexanderGayko.VarAdorner , i managed to get one extension working in VS2017, 2019 and 2022 (basically by reflection-dynamic 'ing around the platform specific parts of the VS packages) - wouldn't that be a better approach for the time being?

**Pull request closed without merging**
