### PR TITLE
Add .sql to PathSegmentFile Nester

### PR DESCRIPTION
**Pull request by lamuleck**
Simplified version of my pull request #47 to simply add .sql to the extension list for Path Segment File Nester

### CODE REVIEW

**Comment by madskristensen** [comment]
Awesome. Thanks :)

**Comment by lamuleck** [comment]
Thanks for babysitting me through my first open source submission.

**Comment by madskristensen** [comment]
Wow, didn't know it was your first. Congrats!!! That's very cool!! :+1:

**Comment by decraw** [comment]
Can you push this version to the gallery?

**Pull request merged**
