### PR TITLE
+ Changed to support Visual Studio 2022

### PR DESCRIPTION
**Pull request by NicoB1981**
I do not work with Git often, so I apologise in advance if I stepped over some etiquette rules. 
I also realise that a pull request is probably not ideal, as my changes will break support for Visual Studio 2017 and prior. I would have followed the Visual Studio guidelines for upgrading extensions to 2022 and created the shared project and second target for VS2022 while keeping VS2017 and below intact, but I couldn’t figure out how to realise this inside the repository’s file structure.
I still opened the pull request, so that somebody else may find this updated version.

Other than that, I followed the guidelines and updated the project for VS2022 (https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022).

•	I migrated packages.config to PackageReference
•	I updated the references for VS2022
•	I updated the vsixmanifest file
 
•	I also changed the compile target to .NET 4.8 and increased the version number (not sure if that is appropriate, but it seemed reasonable to me)

The rest I left unchanged, and the extension still works like a charm. Thanks for the great extension by the way.
If I can do anything further to help, please let me know

### CODE REVIEW

**Comment by ThoamsClark** [comment]
Thank you very much for doing this @NicoB1981.
Had to remove some Shell and Interop references to get it to build with VS2022, done and installed and now it's working perfectly.

Thanks also to Mads, obviously. Thanks for everything over the years.

**Comment by madskristensen** [comment]
File nesting is built in to VS 2022, so not sure how relevant this extension is anymore

**Comment by AdmiralSnyder** [comment]
@madskristensen 
the VS 2022 auto file nesting doesn't appear to work with .net framework projects (OR my config is rubbish)
BUT i need manual nesting for individual files, for example (resulting in <DependentUpon> tags in the .csproj) becaus we don't actually have good rule-ability for when we need to nest files

And since the extension's manual nest dialog is a perfect UI for those manual nestings, i'd really like to keep using the extension. I wasn't aware that this PR exists and thus compiled my own version (where i removed the auto nest menu items) - but it would be so much easier if there was only your extension, canonical, and not a couple others slightly derived away from it :-)

**Comment by ThoamsClark** [comment]
@AdmiralSnyder
You're not alone! File nesting not working for .Net Framework projects in VS2022 is what brought me here too.

@madskristensen
I haven't checked recently to see if it works natively for them now but, as above, I sought a vs2022 compatible version of your extension because file nesting was broken for .Net Framework projects and I was hoping not to have to keep 2019 around for working with old projects.

**Comment by bstordrup** [comment]
@ThoamsClark, @madskristensen, I added a feature request in dotnet/project-system repository for supporting file nesting for legacy projects.

The response was that it was not the correct repository, and the team that should handle it is not tracking feature requests in GitHub. So added it through Developer Community.
But part of the response was also, that the responder (Drew Noakes) doubted it would happen any time 
soon.

So IMO, completing this pull request and adding support for Visual Studio 2022 would be a great idea.

**Comment by precisioninfinity** [comment]
Upvote on this PR, seems to work great and yes have the same problem as others, need support for legacy projects I'm used to having this on older VS.

**Pull request merged**
